### ISSUE TITLE
Where are game controls gonna live?

### ISSUE THREAD

**Issue by Pilipo** [Pilipo/septikon#28]
For that matter what controls are needed??

Roll dice
Warhead indicator
Debug mode

**Comment by luketlancaster** [comment]
I'd imagine that controls would live in the `update` function in the main game logic. 

Roll dice, click on clone + move, 'activate' tiles?

**Comment by Pilipo** [comment]
I think I follow. I don't have my head around the update() block yet. Does it work on a loop or timer or something?

**Comment by luketlancaster** [comment]
Yeah, it runs at 60 times/second. So you'd just be checking to see if a click happened or a key was down or something, then do some work

**Comment by Pilipo** [comment]
Nice. That's easy. 
* Click to roll -> "activate" clones with legal moves available
* Click clone -> "activate" legal spaces
* Click space -> execute move command to server (and a bunch of other crap)

**Comment by Pilipo** [comment]
Added
